#Spring Properties
spring:
  aop:
    auto: true
    proxy-target-class: false
    
  messages:
    basename: messages
    always-use-message-format: false
    cache-seconds: -1
  mvc:
    dispatch-options-request: true
    dispatch-trace-request: false
  couchbase:
    bucket:
      name: default
#Security Properties
security:
  oauth2:
    resource:
      service-id: resource
      prefer-token-info: true
      
    